---
- name: "18.10.12.1 | L1 | Ensure 'Turn off cloud consumer account state content' is set to 'Enabled'"
  when:
    - w2019cis_rule_18_10_12_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\Cloudcontent
    name: DisableConsumerAccountStateContent
    data: 1
    type: dword

- name: "18.10.12.2 | L1 | Ensure 'Turn off Microsoft consumer experiences' is set to 'Enabled'"
  when:
    - w2019cis_rule_18_10_12_2_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\Cloudcontent
    name: DisableWindowsConsumerFeatures
    data: 1
    type: dword
